# COPY markdown files to:
folder: 'nav'
# Don't copy these folder
extra: 
  - 'private'
  - 'assets'
  - 'README.md'

# vuepress config
vuepress: 
  base: '/'
  title: 'Zero Navigation'
  description: 'Just let in links!'
  head:
    - 'meta'
    - name: 'keywords'
      content:
        - 'zero'
        - 'zero navigation'
        - 'develop navigation'
        - 'blog navigation'
        - 'coding navigation'
  dest: 'public'
  # ga: 'UA-xxxxx-1'
  serviceWorker: true
  markdown:
    toc:
      includeLevel: 
        - 2
        - 3
        - 4

  theme: 'nav'
  themeConfig:
    repo: 'zeronav/zeronav.github.io'
    editLinks: true
    nav:
    # navTheme setting
    personalInfo:
      nickname: 'Zero'
      description: 'Love Freedom!'
      email: 'zero#zero.github.io'
      location: 'Utopia'
      organization: 'Link Colection'
      avator: '/assets/zero.png'
    headerBackground:
      useGeo: true
    lastUpdated: true