# COPY markdown files to:
folder: 'nav'
# Don't copy these folder
extra: 
  - 'private'
  - 'README.md'

# vuepress config
vuepress: 
  base: '/'
  title: 'Zero Navigation'
  description: 'Just let in links!'
  head:
    - 'meta'
    - name: 'keywords'
      content:
        - 'zero'
        - 'zero navigation'
        - 'develop navigation'
        - 'blog navigation'
        - 'coding navigation'
  dest: 'public'
  # ga: 'UA-xxxxx-1'
  serviceWorker: true
  markdown:
    toc:
      includeLevel: 
        - 2
        - 3
        - 4

  # theme: 'meteorlxy'
  themeConfig:
    repo: 'zeronav/zeronav.github.io'
    editLinks: false
    nav:
    # meteorlxy setting
    personalInfo:
      nickname: 'ZeroNav'
      description: 'Just let in links!'
      email: 'none'
      location: 'Earth'
      organization: 'ZeroNav Net'
    headerBackground:
      useGeo: true
    lastUpdated: true