language: node_js
node_js:
- 10.4.0
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  keep-history: true
  local-dir: public
  on:
    branch: master
env:
  global:
    secure: KNuP97c6oB8CWkeGbWa1K+FdYrBD7ED/zQIQVlXDfXcNdxmRftH2a3LO/Z8XjHfGNa+Fz9mFMTpeqStpwp9r8Pib4Bx46tiznQ5hjsK+Ay9TURhTbAjnMpZXtHal3MNCIY7CbcKcRIcCS8p1woRtzWvcA1OuWO+JfAg5nGsTxmIsLMYrLtT0ZUuYo89vQdpJRrpoNTh0Mloi0IW2fEFf85qU/aiUGaIq++sU1TcL133U9SpFYqEyFsMPDCrQmT2DCkxAoJvEY/Xg59ifvqBXWMmLrD6LR9AnST9ap7vZTTYXlPZoOcMM1iRAOO8Nucl/NqOhYtWGUrCoBIDLNccxU6/H+WZvqvBmer9IgtKB+ELgKcZXa2Tu3yLyt29IuLlFnerR5TIL/kui442p9yxkd3Um4uDh1aNbEJJDdaoFP9ue0ln4QhOvUgiu8SBuxUkT2euVVqAyCTcrasVC3bT4ty9prVeBdrA5lm1qFf8EF57w2Q1SjEFvGUxRIMLMp0+lFH0iXshl2zaYiW8HPNxuhwPtljBmsQWnisWPEAHhDslZ8RK3d9y861QeAvYS5caqWXwTAU+X3mx2Cp5ezhyJmyFOE3eIbNxc8N1iUFPqgo8owLuwU1m23xJPZ+Lck/VTGXqCX870/lQOTRa3DRsww+nsTjW/KXzGpfRyu6xEFHU=
